#!perl

use strict;
use warnings;
use File::Next;


my $start = shift || '/Users/andy/src';
my $iter = File::Next::files( { descend_filter => sub { $_ ne '.svn' } }, $start );
while ( my $file = $iter->() ) {
    print "$file\n";
}
