#!perl

use strict;
use warnings;
use File::Next;


my @start = @ARGV ? @ARGV : '/Users/andy/src';
my $iter = File::Next::files( {
    descend_filter  => sub { $_ ne '.svn' },
    sort_files      => \&File::Next::sort_standard,
    follow_symlinks => 0,
}, @start );

my $nfiles;
while ( my $file = $iter->() ) {
    ++$nfiles;
    print "$file\n";
}
warn "$nfiles files processed.\n";
